url: https://stb-gaming.github.io/sky-games

permalink: pretty

collections:
  menus:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: menus
    values:
      layout: menu

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - LICENSE
  - plan.md
  - README.md
  - gulpfile.js
  - gemfiles
  - src
  - package.json
  - package-lock.json


plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-redirect-to
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mention
